:toc:
:toc-placement!:

:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :heavy_exclamation_mark:
:warning-caption: :warning:
:caution-caption: :fire:

= Java Coding Exercise
Ron Kurr <rkurr@jvmguy.com>


toc::[]

== Overview
This project is a solution to a sample Java problem I found on the internet.  Having spent the last couple of years implementing JVM solutions using Groovy, I figured this puzzle would be a nice change of pace.

.Problem Statement
[quote, unknown author, unknown source]
____
This coding test uses two files that are publicly accessible over the internet. Each line in both files contains a property value pair separated by an = character. Properties are a string, values are an integer.  The objective of the task is to print each property and the summation of each properties values. The output should be in descending order of value summation.  The files should be processed in parallel. The project should be written in Java using maven.



These are the test file URLs:

https://s3.amazonaws.com/111test-bucket/file1.txt

https://s3.amazonaws.com/111test-bucket/file2.txt





For example:



File A:

a=3

c=5



File B:

a=1

b=2



Output:

c=5

a=4

b=2
____


It doesn't say what version of Java to use and, since I'm not up to speed on Java 9 yet, I'll stick with Java 8.  The Maven requirement should be fun, since I've been doing builds exclusively with Gradle.  I'll have to put on my "way back hat" and try to remember how to set up a project.  There is no mention of testing so I'll stick my my tried-and-true friend Spock.  I've come to really appreciate the power and simplicity it brings to automated testing, especially when combined with Spring. When I saw that we have to process things in parallel, I immediately thought of Java 8's parallel streams, so we'll give that a try.

== Prerequisites
* http://zulu.org/[JDK 8] installed and working
* https://maven.apache.org/[Apache Maven] installed and working
* I developed and tested on an https://app.vagrantup.com/kurron/boxes/xenial-xubuntu[Ubuntu-based Vagrant development box] I maintain, which already has the prerequisites installed

# Building
`./gradlew` will pull down any dependencies, compile the source and package everything up.

== Installation
Nothing to install.

== Tips and Tricks

== Troubleshooting

== Contributing

== License and Credits
* This project is licensed under the http://www.apache.org/licenses/[Apache License Version 2.0, January 2004].
* The guidebook structure was created by http://simonbrown.je/[Simon Brown] as part of his work on the https://c4model.com/[C4 Architectural Model].  His books can be https://leanpub.com/b/software-architecture[purchased from LeanPub].
* Patrick Kua offered https://www.safaribooksonline.com/library/view/oreilly-software-architecture/9781491985274/video315451.html[his thoughts on a travel guide to a software system] which has been travel-guide/travel-guide.md[captured in this template].

== List of Changes
